name = "SorryDBTest423"
version = "0.1.0"
defaultTargets = ["sorrydbtest423"]

[[lean_lib]]
name = "SorryDBTest423"

[[lean_exe]]
name = "sorrydbtest423"
root = "Main"

[[require]]
name = "Hammer"
git = "https://github.com/JOSHCLUNE/LeanHammer"
rev = "v4.23.0"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.23.0"
